(DEFUN c:haws-AEE ()
  (PROMPT "\nSelect object: ")
  (COMMAND "AREA" "E" pause)
  (PRINC "Area=")
  (PRINC (GETVAR "AREA"))
  (PRINC "  Length=")
  (PRINC (GETVAR "PERIMETER"))
  (PRINC "  Area in acres=")
  (PRINC (/ (GETVAR "AREA") 43560))
  (PRINC)
)
