;Written by Thomas Gail Haws
(defun c:haws-contxt (/ txtht txtstr inspt rot)
  (haws-core-borrow 0)
  (HAWS-VSAVE '("clayer"))
  (setvar "cmdecho" 0)
  (setq txtht (* (HAWS-DWGSCALE)(getvar"dimtxt")))
  (setq txtstr (getstring "\nContour text:"))
  (HAWS-MKLAYR "CONTLBL")
  (setq inspt (getpoint "\nMiddle point:") rot (getangle inspt " Rotation: "))
  (HAWS-MKTEXT "m" inspt txtht rot txtstr)
  (HAWS-VRSTOR)(haws-core-return)(princ)
)
