;Written by Thomas Gail Haws
(defun c:haws-contxt (/ txtht txtstr inspt rot)
  (haws-errdef 0)
  (HAWS-VSAVE '("clayer"))
  (setvar "cmdecho" 0)
  (setq txtht (* (HAWS-DWGSCALE)(getvar"dimtxt")))
  (setq txtstr (getstring "\nContour text:"))
  (HAWS-MKLAYR "CONTLBL")
  (setq inspt (getpoint "\nMiddle point:") rot (getangle inspt " Rotation: "))
  (HAWS-MKTEXT "m" inspt txtht rot txtstr)
  (HAWS-VRSTOR)(HAWS-ERRRST)(princ)
)
