(defun c:haws-lengthen ( / opt) 
  (initget "Delta Percent Total") 
  (setq opt (getkword "\nEnter an option [Delta/Percent/Total] <Dynamic>: "))
  (cond ((not opt) (setq opt "Dynamic")))
  (command "._lengthen" opt)
  (princ)
)
